// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: score_info.proto

package score_server;

public final class ScoreInfo {
  private ScoreInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface base_score_info_tOrBuilder extends
      // @@protoc_insertion_point(interface_extends:score_server.base_score_info_t)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 玩家胜局局数
     * </pre>
     *
     * <code>optional int32 win_count = 1;</code>
     * @return Whether the winCount field is set.
     */
    boolean hasWinCount();
    /**
     * <pre>
     * 玩家胜局局数
     * </pre>
     *
     * <code>optional int32 win_count = 1;</code>
     * @return The winCount.
     */
    int getWinCount();

    /**
     * <pre>
     * 玩家负局局数
     * </pre>
     *
     * <code>optional int32 lose_count = 2;</code>
     * @return Whether the loseCount field is set.
     */
    boolean hasLoseCount();
    /**
     * <pre>
     * 玩家负局局数
     * </pre>
     *
     * <code>optional int32 lose_count = 2;</code>
     * @return The loseCount.
     */
    int getLoseCount();

    /**
     * <pre>
     * 玩家异常局局数
     * </pre>
     *
     * <code>optional int32 exception_count = 3;</code>
     * @return Whether the exceptionCount field is set.
     */
    boolean hasExceptionCount();
    /**
     * <pre>
     * 玩家异常局局数
     * </pre>
     *
     * <code>optional int32 exception_count = 3;</code>
     * @return The exceptionCount.
     */
    int getExceptionCount();

    /**
     * <pre>
     * 总人头数
     * </pre>
     *
     * <code>optional int32 kill_count = 4;</code>
     * @return Whether the killCount field is set.
     */
    boolean hasKillCount();
    /**
     * <pre>
     * 总人头数
     * </pre>
     *
     * <code>optional int32 kill_count = 4;</code>
     * @return The killCount.
     */
    int getKillCount();

    /**
     * <pre>
     * 总死亡数
     * </pre>
     *
     * <code>optional int32 death_count = 5;</code>
     * @return Whether the deathCount field is set.
     */
    boolean hasDeathCount();
    /**
     * <pre>
     * 总死亡数
     * </pre>
     *
     * <code>optional int32 death_count = 5;</code>
     * @return The deathCount.
     */
    int getDeathCount();

    /**
     * <pre>
     * 总总助攻数
     * </pre>
     *
     * <code>optional int32 assist_count = 6;</code>
     * @return Whether the assistCount field is set.
     */
    boolean hasAssistCount();
    /**
     * <pre>
     * 总总助攻数
     * </pre>
     *
     * <code>optional int32 assist_count = 6;</code>
     * @return The assistCount.
     */
    int getAssistCount();

    /**
     * <pre>
     * 评价积分
     * </pre>
     *
     * <code>optional int64 rating = 7;</code>
     * @return Whether the rating field is set.
     */
    boolean hasRating();
    /**
     * <pre>
     * 评价积分
     * </pre>
     *
     * <code>optional int64 rating = 7;</code>
     * @return The rating.
     */
    long getRating();
  }
  /**
   * <pre>
   **
   * &#64;brief base_score_info
   * </pre>
   *
   * Protobuf type {@code score_server.base_score_info_t}
   */
  public  static final class base_score_info_t extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:score_server.base_score_info_t)
      base_score_info_tOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use base_score_info_t.newBuilder() to construct.
    private base_score_info_t(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private base_score_info_t() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new base_score_info_t();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private base_score_info_t(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              winCount_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              loseCount_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              exceptionCount_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              killCount_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              deathCount_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              assistCount_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              rating_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return score_server.ScoreInfo.internal_static_score_server_base_score_info_t_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return score_server.ScoreInfo.internal_static_score_server_base_score_info_t_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              score_server.ScoreInfo.base_score_info_t.class, score_server.ScoreInfo.base_score_info_t.Builder.class);
    }

    private int bitField0_;
    public static final int WIN_COUNT_FIELD_NUMBER = 1;
    private int winCount_;
    /**
     * <pre>
     * 玩家胜局局数
     * </pre>
     *
     * <code>optional int32 win_count = 1;</code>
     * @return Whether the winCount field is set.
     */
    public boolean hasWinCount() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * 玩家胜局局数
     * </pre>
     *
     * <code>optional int32 win_count = 1;</code>
     * @return The winCount.
     */
    public int getWinCount() {
      return winCount_;
    }

    public static final int LOSE_COUNT_FIELD_NUMBER = 2;
    private int loseCount_;
    /**
     * <pre>
     * 玩家负局局数
     * </pre>
     *
     * <code>optional int32 lose_count = 2;</code>
     * @return Whether the loseCount field is set.
     */
    public boolean hasLoseCount() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * 玩家负局局数
     * </pre>
     *
     * <code>optional int32 lose_count = 2;</code>
     * @return The loseCount.
     */
    public int getLoseCount() {
      return loseCount_;
    }

    public static final int EXCEPTION_COUNT_FIELD_NUMBER = 3;
    private int exceptionCount_;
    /**
     * <pre>
     * 玩家异常局局数
     * </pre>
     *
     * <code>optional int32 exception_count = 3;</code>
     * @return Whether the exceptionCount field is set.
     */
    public boolean hasExceptionCount() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * 玩家异常局局数
     * </pre>
     *
     * <code>optional int32 exception_count = 3;</code>
     * @return The exceptionCount.
     */
    public int getExceptionCount() {
      return exceptionCount_;
    }

    public static final int KILL_COUNT_FIELD_NUMBER = 4;
    private int killCount_;
    /**
     * <pre>
     * 总人头数
     * </pre>
     *
     * <code>optional int32 kill_count = 4;</code>
     * @return Whether the killCount field is set.
     */
    public boolean hasKillCount() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * 总人头数
     * </pre>
     *
     * <code>optional int32 kill_count = 4;</code>
     * @return The killCount.
     */
    public int getKillCount() {
      return killCount_;
    }

    public static final int DEATH_COUNT_FIELD_NUMBER = 5;
    private int deathCount_;
    /**
     * <pre>
     * 总死亡数
     * </pre>
     *
     * <code>optional int32 death_count = 5;</code>
     * @return Whether the deathCount field is set.
     */
    public boolean hasDeathCount() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * 总死亡数
     * </pre>
     *
     * <code>optional int32 death_count = 5;</code>
     * @return The deathCount.
     */
    public int getDeathCount() {
      return deathCount_;
    }

    public static final int ASSIST_COUNT_FIELD_NUMBER = 6;
    private int assistCount_;
    /**
     * <pre>
     * 总总助攻数
     * </pre>
     *
     * <code>optional int32 assist_count = 6;</code>
     * @return Whether the assistCount field is set.
     */
    public boolean hasAssistCount() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * 总总助攻数
     * </pre>
     *
     * <code>optional int32 assist_count = 6;</code>
     * @return The assistCount.
     */
    public int getAssistCount() {
      return assistCount_;
    }

    public static final int RATING_FIELD_NUMBER = 7;
    private long rating_;
    /**
     * <pre>
     * 评价积分
     * </pre>
     *
     * <code>optional int64 rating = 7;</code>
     * @return Whether the rating field is set.
     */
    public boolean hasRating() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * 评价积分
     * </pre>
     *
     * <code>optional int64 rating = 7;</code>
     * @return The rating.
     */
    public long getRating() {
      return rating_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, winCount_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, loseCount_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, exceptionCount_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, killCount_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(5, deathCount_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeInt32(6, assistCount_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeInt64(7, rating_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, winCount_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, loseCount_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, exceptionCount_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, killCount_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, deathCount_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, assistCount_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, rating_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof score_server.ScoreInfo.base_score_info_t)) {
        return super.equals(obj);
      }
      score_server.ScoreInfo.base_score_info_t other = (score_server.ScoreInfo.base_score_info_t) obj;

      if (hasWinCount() != other.hasWinCount()) return false;
      if (hasWinCount()) {
        if (getWinCount()
            != other.getWinCount()) return false;
      }
      if (hasLoseCount() != other.hasLoseCount()) return false;
      if (hasLoseCount()) {
        if (getLoseCount()
            != other.getLoseCount()) return false;
      }
      if (hasExceptionCount() != other.hasExceptionCount()) return false;
      if (hasExceptionCount()) {
        if (getExceptionCount()
            != other.getExceptionCount()) return false;
      }
      if (hasKillCount() != other.hasKillCount()) return false;
      if (hasKillCount()) {
        if (getKillCount()
            != other.getKillCount()) return false;
      }
      if (hasDeathCount() != other.hasDeathCount()) return false;
      if (hasDeathCount()) {
        if (getDeathCount()
            != other.getDeathCount()) return false;
      }
      if (hasAssistCount() != other.hasAssistCount()) return false;
      if (hasAssistCount()) {
        if (getAssistCount()
            != other.getAssistCount()) return false;
      }
      if (hasRating() != other.hasRating()) return false;
      if (hasRating()) {
        if (getRating()
            != other.getRating()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasWinCount()) {
        hash = (37 * hash) + WIN_COUNT_FIELD_NUMBER;
        hash = (53 * hash) + getWinCount();
      }
      if (hasLoseCount()) {
        hash = (37 * hash) + LOSE_COUNT_FIELD_NUMBER;
        hash = (53 * hash) + getLoseCount();
      }
      if (hasExceptionCount()) {
        hash = (37 * hash) + EXCEPTION_COUNT_FIELD_NUMBER;
        hash = (53 * hash) + getExceptionCount();
      }
      if (hasKillCount()) {
        hash = (37 * hash) + KILL_COUNT_FIELD_NUMBER;
        hash = (53 * hash) + getKillCount();
      }
      if (hasDeathCount()) {
        hash = (37 * hash) + DEATH_COUNT_FIELD_NUMBER;
        hash = (53 * hash) + getDeathCount();
      }
      if (hasAssistCount()) {
        hash = (37 * hash) + ASSIST_COUNT_FIELD_NUMBER;
        hash = (53 * hash) + getAssistCount();
      }
      if (hasRating()) {
        hash = (37 * hash) + RATING_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getRating());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static score_server.ScoreInfo.base_score_info_t parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static score_server.ScoreInfo.base_score_info_t parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static score_server.ScoreInfo.base_score_info_t parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static score_server.ScoreInfo.base_score_info_t parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static score_server.ScoreInfo.base_score_info_t parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static score_server.ScoreInfo.base_score_info_t parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static score_server.ScoreInfo.base_score_info_t parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static score_server.ScoreInfo.base_score_info_t parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static score_server.ScoreInfo.base_score_info_t parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static score_server.ScoreInfo.base_score_info_t parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static score_server.ScoreInfo.base_score_info_t parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static score_server.ScoreInfo.base_score_info_t parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(score_server.ScoreInfo.base_score_info_t prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     * &#64;brief base_score_info
     * </pre>
     *
     * Protobuf type {@code score_server.base_score_info_t}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:score_server.base_score_info_t)
        score_server.ScoreInfo.base_score_info_tOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return score_server.ScoreInfo.internal_static_score_server_base_score_info_t_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return score_server.ScoreInfo.internal_static_score_server_base_score_info_t_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                score_server.ScoreInfo.base_score_info_t.class, score_server.ScoreInfo.base_score_info_t.Builder.class);
      }

      // Construct using score_server.ScoreInfo.base_score_info_t.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        winCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        loseCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        exceptionCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        killCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        deathCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        assistCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        rating_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return score_server.ScoreInfo.internal_static_score_server_base_score_info_t_descriptor;
      }

      @java.lang.Override
      public score_server.ScoreInfo.base_score_info_t getDefaultInstanceForType() {
        return score_server.ScoreInfo.base_score_info_t.getDefaultInstance();
      }

      @java.lang.Override
      public score_server.ScoreInfo.base_score_info_t build() {
        score_server.ScoreInfo.base_score_info_t result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public score_server.ScoreInfo.base_score_info_t buildPartial() {
        score_server.ScoreInfo.base_score_info_t result = new score_server.ScoreInfo.base_score_info_t(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.winCount_ = winCount_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.loseCount_ = loseCount_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.exceptionCount_ = exceptionCount_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.killCount_ = killCount_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.deathCount_ = deathCount_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.assistCount_ = assistCount_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.rating_ = rating_;
          to_bitField0_ |= 0x00000040;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof score_server.ScoreInfo.base_score_info_t) {
          return mergeFrom((score_server.ScoreInfo.base_score_info_t)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(score_server.ScoreInfo.base_score_info_t other) {
        if (other == score_server.ScoreInfo.base_score_info_t.getDefaultInstance()) return this;
        if (other.hasWinCount()) {
          setWinCount(other.getWinCount());
        }
        if (other.hasLoseCount()) {
          setLoseCount(other.getLoseCount());
        }
        if (other.hasExceptionCount()) {
          setExceptionCount(other.getExceptionCount());
        }
        if (other.hasKillCount()) {
          setKillCount(other.getKillCount());
        }
        if (other.hasDeathCount()) {
          setDeathCount(other.getDeathCount());
        }
        if (other.hasAssistCount()) {
          setAssistCount(other.getAssistCount());
        }
        if (other.hasRating()) {
          setRating(other.getRating());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        score_server.ScoreInfo.base_score_info_t parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (score_server.ScoreInfo.base_score_info_t) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int winCount_ ;
      /**
       * <pre>
       * 玩家胜局局数
       * </pre>
       *
       * <code>optional int32 win_count = 1;</code>
       * @return Whether the winCount field is set.
       */
      public boolean hasWinCount() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * 玩家胜局局数
       * </pre>
       *
       * <code>optional int32 win_count = 1;</code>
       * @return The winCount.
       */
      public int getWinCount() {
        return winCount_;
      }
      /**
       * <pre>
       * 玩家胜局局数
       * </pre>
       *
       * <code>optional int32 win_count = 1;</code>
       * @param value The winCount to set.
       * @return This builder for chaining.
       */
      public Builder setWinCount(int value) {
        bitField0_ |= 0x00000001;
        winCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 玩家胜局局数
       * </pre>
       *
       * <code>optional int32 win_count = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearWinCount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        winCount_ = 0;
        onChanged();
        return this;
      }

      private int loseCount_ ;
      /**
       * <pre>
       * 玩家负局局数
       * </pre>
       *
       * <code>optional int32 lose_count = 2;</code>
       * @return Whether the loseCount field is set.
       */
      public boolean hasLoseCount() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * 玩家负局局数
       * </pre>
       *
       * <code>optional int32 lose_count = 2;</code>
       * @return The loseCount.
       */
      public int getLoseCount() {
        return loseCount_;
      }
      /**
       * <pre>
       * 玩家负局局数
       * </pre>
       *
       * <code>optional int32 lose_count = 2;</code>
       * @param value The loseCount to set.
       * @return This builder for chaining.
       */
      public Builder setLoseCount(int value) {
        bitField0_ |= 0x00000002;
        loseCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 玩家负局局数
       * </pre>
       *
       * <code>optional int32 lose_count = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLoseCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        loseCount_ = 0;
        onChanged();
        return this;
      }

      private int exceptionCount_ ;
      /**
       * <pre>
       * 玩家异常局局数
       * </pre>
       *
       * <code>optional int32 exception_count = 3;</code>
       * @return Whether the exceptionCount field is set.
       */
      public boolean hasExceptionCount() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * 玩家异常局局数
       * </pre>
       *
       * <code>optional int32 exception_count = 3;</code>
       * @return The exceptionCount.
       */
      public int getExceptionCount() {
        return exceptionCount_;
      }
      /**
       * <pre>
       * 玩家异常局局数
       * </pre>
       *
       * <code>optional int32 exception_count = 3;</code>
       * @param value The exceptionCount to set.
       * @return This builder for chaining.
       */
      public Builder setExceptionCount(int value) {
        bitField0_ |= 0x00000004;
        exceptionCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 玩家异常局局数
       * </pre>
       *
       * <code>optional int32 exception_count = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearExceptionCount() {
        bitField0_ = (bitField0_ & ~0x00000004);
        exceptionCount_ = 0;
        onChanged();
        return this;
      }

      private int killCount_ ;
      /**
       * <pre>
       * 总人头数
       * </pre>
       *
       * <code>optional int32 kill_count = 4;</code>
       * @return Whether the killCount field is set.
       */
      public boolean hasKillCount() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * 总人头数
       * </pre>
       *
       * <code>optional int32 kill_count = 4;</code>
       * @return The killCount.
       */
      public int getKillCount() {
        return killCount_;
      }
      /**
       * <pre>
       * 总人头数
       * </pre>
       *
       * <code>optional int32 kill_count = 4;</code>
       * @param value The killCount to set.
       * @return This builder for chaining.
       */
      public Builder setKillCount(int value) {
        bitField0_ |= 0x00000008;
        killCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 总人头数
       * </pre>
       *
       * <code>optional int32 kill_count = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearKillCount() {
        bitField0_ = (bitField0_ & ~0x00000008);
        killCount_ = 0;
        onChanged();
        return this;
      }

      private int deathCount_ ;
      /**
       * <pre>
       * 总死亡数
       * </pre>
       *
       * <code>optional int32 death_count = 5;</code>
       * @return Whether the deathCount field is set.
       */
      public boolean hasDeathCount() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       * 总死亡数
       * </pre>
       *
       * <code>optional int32 death_count = 5;</code>
       * @return The deathCount.
       */
      public int getDeathCount() {
        return deathCount_;
      }
      /**
       * <pre>
       * 总死亡数
       * </pre>
       *
       * <code>optional int32 death_count = 5;</code>
       * @param value The deathCount to set.
       * @return This builder for chaining.
       */
      public Builder setDeathCount(int value) {
        bitField0_ |= 0x00000010;
        deathCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 总死亡数
       * </pre>
       *
       * <code>optional int32 death_count = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeathCount() {
        bitField0_ = (bitField0_ & ~0x00000010);
        deathCount_ = 0;
        onChanged();
        return this;
      }

      private int assistCount_ ;
      /**
       * <pre>
       * 总总助攻数
       * </pre>
       *
       * <code>optional int32 assist_count = 6;</code>
       * @return Whether the assistCount field is set.
       */
      public boolean hasAssistCount() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <pre>
       * 总总助攻数
       * </pre>
       *
       * <code>optional int32 assist_count = 6;</code>
       * @return The assistCount.
       */
      public int getAssistCount() {
        return assistCount_;
      }
      /**
       * <pre>
       * 总总助攻数
       * </pre>
       *
       * <code>optional int32 assist_count = 6;</code>
       * @param value The assistCount to set.
       * @return This builder for chaining.
       */
      public Builder setAssistCount(int value) {
        bitField0_ |= 0x00000020;
        assistCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 总总助攻数
       * </pre>
       *
       * <code>optional int32 assist_count = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearAssistCount() {
        bitField0_ = (bitField0_ & ~0x00000020);
        assistCount_ = 0;
        onChanged();
        return this;
      }

      private long rating_ ;
      /**
       * <pre>
       * 评价积分
       * </pre>
       *
       * <code>optional int64 rating = 7;</code>
       * @return Whether the rating field is set.
       */
      public boolean hasRating() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <pre>
       * 评价积分
       * </pre>
       *
       * <code>optional int64 rating = 7;</code>
       * @return The rating.
       */
      public long getRating() {
        return rating_;
      }
      /**
       * <pre>
       * 评价积分
       * </pre>
       *
       * <code>optional int64 rating = 7;</code>
       * @param value The rating to set.
       * @return This builder for chaining.
       */
      public Builder setRating(long value) {
        bitField0_ |= 0x00000040;
        rating_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 评价积分
       * </pre>
       *
       * <code>optional int64 rating = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearRating() {
        bitField0_ = (bitField0_ & ~0x00000040);
        rating_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:score_server.base_score_info_t)
    }

    // @@protoc_insertion_point(class_scope:score_server.base_score_info_t)
    private static final score_server.ScoreInfo.base_score_info_t DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new score_server.ScoreInfo.base_score_info_t();
    }

    public static score_server.ScoreInfo.base_score_info_t getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<base_score_info_t>
        PARSER = new com.google.protobuf.AbstractParser<base_score_info_t>() {
      @java.lang.Override
      public base_score_info_t parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new base_score_info_t(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<base_score_info_t> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<base_score_info_t> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public score_server.ScoreInfo.base_score_info_t getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_score_server_base_score_info_t_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_score_server_base_score_info_t_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020score_info.proto\022\014score_server\"\242\001\n\021bas" +
      "e_score_info_t\022\021\n\twin_count\030\001 \001(\005\022\022\n\nlos" +
      "e_count\030\002 \001(\005\022\027\n\017exception_count\030\003 \001(\005\022\022" +
      "\n\nkill_count\030\004 \001(\005\022\023\n\013death_count\030\005 \001(\005\022" +
      "\024\n\014assist_count\030\006 \001(\005\022\016\n\006rating\030\007 \001(\003"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_score_server_base_score_info_t_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_score_server_base_score_info_t_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_score_server_base_score_info_t_descriptor,
        new java.lang.String[] { "WinCount", "LoseCount", "ExceptionCount", "KillCount", "DeathCount", "AssistCount", "Rating", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
