apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: new-namespace
spec:
  ports:
    - port: 27017
      nodePort: 31017
      targetPort: 27017
      protocol: TCP
  selector:
    app: mongo-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment-demo
  namespace: new-namespace
  labels:
    app: mongo-deployment-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
