// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: score_info.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ScoreInfoRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ScoreInfoRoot : GPBRootObject
@end

#pragma mark - base_score_info_t

typedef GPB_ENUM(base_score_info_t_FieldNumber) {
  base_score_info_t_FieldNumber_WinCount = 1,
  base_score_info_t_FieldNumber_LoseCount = 2,
  base_score_info_t_FieldNumber_ExceptionCount = 3,
  base_score_info_t_FieldNumber_KillCount = 4,
  base_score_info_t_FieldNumber_DeathCount = 5,
  base_score_info_t_FieldNumber_AssistCount = 6,
  base_score_info_t_FieldNumber_Rating = 7,
};

/**
 * *
 * \@brief base_score_info
 **/
@interface base_score_info_t : GPBMessage

/** 玩家胜局局数 */
@property(nonatomic, readwrite) int32_t winCount;

@property(nonatomic, readwrite) BOOL hasWinCount;
/** 玩家负局局数 */
@property(nonatomic, readwrite) int32_t loseCount;

@property(nonatomic, readwrite) BOOL hasLoseCount;
/** 玩家异常局局数 */
@property(nonatomic, readwrite) int32_t exceptionCount;

@property(nonatomic, readwrite) BOOL hasExceptionCount;
/** 总人头数 */
@property(nonatomic, readwrite) int32_t killCount;

@property(nonatomic, readwrite) BOOL hasKillCount;
/** 总死亡数 */
@property(nonatomic, readwrite) int32_t deathCount;

@property(nonatomic, readwrite) BOOL hasDeathCount;
/** 总总助攻数 */
@property(nonatomic, readwrite) int32_t assistCount;

@property(nonatomic, readwrite) BOOL hasAssistCount;
/** 评价积分 */
@property(nonatomic, readwrite) int64_t rating;

@property(nonatomic, readwrite) BOOL hasRating;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
